### ISSUE TITLE
Tracking references after idea generation

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#47]
**Context**
Reporting this on behalf of a first time user.

**Describe the bug**
User was unable to identify the paper referenced in the literature review text, because the paper cards in the bottom were not numbered.

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[x] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Reality: No numbers for paper cards.
Expectation: Each paper card should have a number which matches the way it is references in the text (idea summary or literature review).

**Screenshots**
![image](https://github.com/user-attachments/assets/6981d642-d20f-4472-91b9-52a10332b5df)

**Desktop (if applicable):**
 - OS: Windows
 - Browser Edge Dev

**Additional context**
User email: a.habashy@ieee.org

Thank you for improving the Idea Factory!!

**Comment by wammar** [comment]
Next step for this task is to improve the design. Assigning to @Iryna-Boboshko

**Comment by muhammadnasr** [comment]
@Iryna-Boboshko any updates on this.

**Comment by Iryna-Boboshko** [comment]
Video - https://www.loom.com/share/0decc7ab0a4f4288a285f00e0fb57e1b?sid=7888b680-f590-4135-80e8-7ae8d9a8b5f8

Figma - https://www.figma.com/design/NWE1wGpmYw2UJGqoElS6WO/SeeChat-x-Ideas-(v7)?node-id=173-42542&t=MZT7bsrrw9evkv8C-1

<img width="332" alt="image" src="https://github.com/user-attachments/assets/28569613-9f55-4a51-82cb-0617dc52afdf">

**Comment by wammar** [comment]
Great progress on this @Iryna-Boboshko but the extra line is unnecessary. Let's:
- [ ] Instead of the full date, let's use only the year, and put it on the same line with the author names at the beginning. 
- [ ] Year should be more colorful than the rest, but different from the # of citations.
- [ ] Number of citations should be on the same line with the paper title, at the end.

**Comment by Iryna-Boboshko** [comment]
@wammar fixed the Paper reference card. I am unsure about this red color (blue is already used for the citations). Maybe we can try a black color?

![Image](https://github.com/user-attachments/assets/2bfe4f1c-1851-4e42-8d04-bf528b99c58b)

**Comment by wammar** [comment]
Looks great!
